#include <dia2.h>


wchar_t* strs[] = {
	L"NtGdiCreateCompatibleDC",
	L"NtGdiGetDIBitsInternal",
	L"NtUserGetDC",
	L"NtGdiGetDeviceCaps",
	L"NtGdiOpenDCW",
	L"NtGdiCreateCompatibleBitmap",
	L"NtGdiDeleteObjectApp",
	L"NtGdiBitBlt",
	L"NtProtectVirtualMemory",
	L"NtSetInformationThread",
	L"NtCreateFile",
	L"NtGdiCreateDIBSection",
	L"NtGdiExtGetObjectW",
	L"NtGdiFlush",
	L"NtGdiStretchBlt",
	L"NtQuerySystemInformation",
	L"NtFlushInstructionCache",
	L"NtQueryAttributesFile",
	L"NtOpenFile",
	L"NtCreateSection",
	L"NtQuerySection",
	L"NtOpenKeyEx",
	L"NtQueryValueKey",
	L"NtOpenSection",
	L"NtQueryKey",
	L"NtUserGetForegroundWindow",
	L"NtUserQueryWindow",
	L"NtUserGetKeyState",
	L"NtUserGetKeyboardState",
	L"NtUserToUnicodeEx",
	L"NtUserMapVirtualKeyEx",
	L"NtSetInformationFile",
	L"NtAlpcConnectPort",
	L"NtEnumerateValueKey",
	L"NtQueryObject",
	L"NtCreateKey",
	L"NtOpenEvent",
	L"NtTraceControl",
	L"NtUserRegisterWindowMessage"
	};

